Update README to register notifications before starting reading them
uber/RxCBCentral pull request #26
Opened 2020-10-28 13:12 UTC by alinekborges

`peripheralManager.receiveNotifications` only works after actually registering to receive that notification. I added a line in the readme to reflect this configuration needing to be set before using it

2020-10-28 22:23 UTC, jpsoultanis requested changes

2020-10-28 22:23 UTC, jpsoultanis commented on README.md
> +        return self.pheripheralManager.queue(operation: RegisterNotification(service: serviceUUID, characteristic: characteristicUUID))
peripheralManager is misspelled, would you mind fixing?

2021-01-21 12:53 UTC, mustafagunes requested changes

2021-01-21 12:53 UTC, mustafagunes commented on README.md
> +        return self.pheripheralManager.queue(operation: RegisterNotification(service: serviceUUID, characteristic: characteristicUUID))
```suggestion
    .flatMapLatest{ _ -> Observable<()>
        // register to listen to pheripheral notifications
        let operation = RegisterNotification(service: serviceUUID, characteristic: characteristicUUID)
        return self.peripheralManager.queue(operation: operation)
```

That's how you can change it :)

2021-06-21 06:40 UTC, merged